name: Publish

on:
  push:
    branches:
      - main
    # tags:
    # - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  publish-npm:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: 12
            registry-url: https://registry.npmjs.org/
        - run: yarn install --frozen-lockfile
        - run: yarn build
        - run: npm publish
          env:
            TAG: ${{ github.event.release.tag_name }}
            NODE_AUTH_TOKEN: ${{ secrets.YARN_TOKEN }}

  publish-gh:
      needs: publish-npm
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: 12
            registry-url: https://npm.pkg.github.com/
        - run: yarn install --frozen-lockfile
        - run: yarn build
        - run: echo $TAG
        - run: npm publish
          env:
            NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
