name: Publish

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'tag / version to publish'
        required: true
        default: 'v0.0.0'
jobs:
  publish-npm:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: 12
            registry-url: https://registry.npmjs.org/
            scope: '@alexanderjeurissen'
        - run: yarn install --frozen-lockfile
        - run: yarn build
        - run: npm publish --access public
          env:
            TAG: ${{ github.event.inputs.tag_name }}
            NODE_AUTH_TOKEN: ${{ secrets.YARN_TOKEN }}

  publish-gpr:
      needs: publish-npm
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: 12
            registry-url: https://npm.pkg.github.com/
            scope: '@alexanderjeurissen'
        - run: yarn install --frozen-lockfile
        - run: yarn build
        - run: npm publish --access public
          env:
            NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
